#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${HDFS_USER}" ]]; then
  echo "Missing HDFS_USER environment variable" >&2
  exit 1
fi
# Create user for HDFS
adduser --no-create-home --disabled-password --gecos "" $HDFS_USER
# Fix directory permissions
chown -R $HDFS_USER:$HDFS_USER /opt/hdfs
chown -R $HDFS_USER:$HDFS_USER $HADOOP_HOME
# Select node type
if [[ "${1}" = 'namenode' ]]; then
  su $HDFS_USER -c "/opt/util/bin/start-hadoop-namenode $2"
elif [[ "${1}" =  'datanode' ]]; then
  su $HDFS_USER -c "/opt/util/bin/start-hadoop-datanode $2 $3"
else
  echo "Invalid command '${1}'" >&2
  exit 1
fi
